### ISSUE TITLE
Screen do not fit to monitor

### ISSUE THREAD

**Issue by edson-acordi** [hneemann/Oscilloscope#1]
Hello hneemann, I am using your Digital software and thank you for share one more great FOSS software!
I try to use the Oscilloscope, however, the screen do not fit in my monitor. I am using the maximum resolution of my monitor 1366x768.
Is possible to implement an option to scroll the screen of Oscilloscope or to set a scale to fit in any monitor?
Thank you.

**Comment by hneemann** [comment]
Of course that would be possible! But I expect to use this piece of software only one last time next week. So I don't think it's worth the effort anymore. And I hope that my students will be able to use a real oscilloscope in the lab again next semester.

**Comment by hneemann** [comment]
@edson-acordi 
Please try the attached zip file.

[Osco.zip](https://github.com/hneemann/Oscilloscope/files/4731811/Osco.zip)

**Comment by edson-acordi** [comment]
Hi @hneemann, yes, it worked!
Thank you again!

**Comment by hneemann** [comment]
closed in 0d35b96480f6769a1a1b62a7b07c5ed9f4c860e2
